### ISSUE TITLE
allow default privacy list to be set

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-registration-plugin#3]
...Migrated from [Ignite Jira OF-1364](https://issues.igniterealtime.org/browse/OF-1364)...

[Ignite Forum Post](https://discourse.igniterealtime.org/t/default-privacy-list-on-account-registration/76623)

When creating a new user, it would be handy if a default privacy list can be defined. Gugli contributed a change to the registration plugin that allows for this.

**Comment by guusdk** [comment]
This was added in version 1.7.1 of the plugin (released in July 2017). I suspect we simply forgot to close the JIRA issue at that time.

This is the commit where the code got added: https://github.com/igniterealtime/openfire-registration-plugin/commit/bf72e7b288ac017e518f5d6bc526a54bd9af1d71
