### ISSUE TITLE
Garbled menu text when using Russian translation

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-registration-plugin#6]
This was marked as Fixed for 4.3.0 release, but i don't see Registration plugin's translation files touched by https://github.com/igniterealtime/Openfire/pull/1174/files it is just mentioned in the changelog. Also 1.7.3 version hasn't been released. So, if the fix is in, maybe it can be released (i can do this). This is the only fix, but i don't see any other fixes coming for this plugin anytime soon, so why wait?

**Comment by wrooot** [comment]
@guusdk ?

**Comment by guusdk** [comment]
I'm thinking that, as the Russian i18n file already contains "readable" unicode (as opposed to escaped characters), the current state is correct. Can you verify (maybe using a nightly), that things are OK?

**Comment by wrooot** [comment]
1.7.3 snapshot works ok.
